services:
  tracker-backend:
    build: .
    container_name: tracker-backend
    restart: unless-stopped
    network_mode: host
    environment:
      - EMQX_API_URL=${EMQX_API_URL}
      - EMQX_API_KEY=${EMQX_API_KEY}
      - EMQX_SECRET_KEY=${EMQX_SECRET_KEY}
      - FIREBASE_ADMIN_SDK_JSON=${FIREBASE_ADMIN_SDK_JSON}
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}